In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import statsmodels.api as sm

In [3]:
from sklearn.datasets import load_boston

In [4]:
boston = load_boston()

In [8]:
X0, y = pd.DataFrame(boston['data'], columns=boston['feature_names']), pd.DataFrame(boston['target'], columns=['MEDV'])

In [10]:
df = sm.add_constant(pd.concat([X0, y], axis=1))
df.head()

,const,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,1.0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98,24.0
1,1.0,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14,21.6
2,1.0,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03,34.7
3,1.0,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94,33.4
4,1.0,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33,36.2

In [39]:
list(df.columns[:-1].values)
model = sm.OLS.from_formula('MEDV ~ +const+CRIM+ZN+INDUS+CHAS+NOX+RM+AGE+DIS+RAD+TAX+PTRATIO+B+LSTAT', data=df)

In [40]:
rlt = model.fit()

In [41]:
rlt.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                   MEDV   R-squared:                       0.741
Model:                            OLS   Adj. R-squared:                  0.734
Method:                 Least Squares   F-statistic:                     108.1
Date:                Mon, 06 Sep 2021   Prob (F-statistic):          6.72e-135
Time:                        10:50:23   Log-Likelihood:                -1498.8
No. Observations:                 506   AIC:                             3026.
Df Residuals:                     492   BIC:                             3085.
Df Model:                          13
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     18.2297      2.552      7.144      0.000      13.216      23.243
const         18.2297      2.552      7.144      0.000      13.216      23.243
CRIM          -0.1080      0.033     -3.287      0.001      -0.173      -0.043
ZN             0.0464      0.014      3.382      0.001       0.019       0.073
INDUS          0.0206      0.061      0.334      0.738      -0.100       0.141
CHAS           2.6867      0.862      3.118      0.002       0.994       4.380
NOX          -17.7666      3.820     -4.651      0.000     -25.272     -10.262
RM             3.8099      0.418      9.116      0.000       2.989       4.631
AGE            0.0007      0.013      0.052      0.958      -0.025       0.027
DIS           -1.4756      0.199     -7.398      0.000      -1.867      -1.084
RAD            0.3060      0.066      4.613      0.000       0.176       0.436
TAX           -0.0123      0.004     -3.280      0.001      -0.020      -0.005
PTRATIO       -0.9527      0.131     -7.283      0.000      -1.210      -0.696
B              0.0093      0.003      3.467      0.001       0.004       0.015
LSTAT         -0.5248      0.051    -10.347      0.000      -0.624      -0.425
==============================================================================
Omnibus:                      178.041   Durbin-Watson:                   1.078
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              783.126
Skew:                           1.521   Prob(JB):                    8.84e-171
Kurtosis:                       8.281   Cond. No.                     7.06e+16
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 3.18e-26. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [45]:
sm.stats.anova_lm(rlt, typ=2)

                sum_sq     df           F        PR(>F)
const      1149.261683    1.0   51.037796  3.283438e-12
CRIM        243.219699    1.0   10.801193  1.086810e-03
ZN          257.492979    1.0   11.435058  7.781097e-04
INDUS         2.516668    1.0    0.111763  7.382881e-01
CHAS        218.970357    1.0    9.724299  1.925030e-03
NOX         487.155674    1.0   21.634196  4.245644e-06
RM         1871.324082    1.0   83.104012  1.979441e-18
AGE           0.061834    1.0    0.002746  9.582293e-01
DIS        1232.412493    1.0   54.730457  6.013491e-13
RAD         479.153926    1.0   21.278844  5.070529e-06
TAX         242.257440    1.0   10.758460  1.111637e-03
PTRATIO    1194.233533    1.0   53.034960  1.308835e-12
B           270.634230    1.0   12.018651  5.728592e-04
LSTAT      2410.838689    1.0  107.063426  7.776912e-23
Residual  11078.784578  492.0         NaN           NaN

In [46]:
sm.stats.anova_lm(rlt)

             df        sum_sq       mean_sq           F        PR(>F)
const       1.0      2.156920      2.156920    0.095787  7.570761e-01
CRIM        1.0   6438.627070   6438.627070  285.934300  6.653224e-51
ZN          1.0   3554.664808   3554.664808  157.859833  1.349221e-31
INDUS       1.0   2563.129897   2563.129897  113.826557  4.795129e-24
CHAS        1.0   1527.677434   1527.677434   67.842938  1.610604e-15
NOX         1.0     73.421592     73.421592    3.260594  7.157447e-02
RM          1.0  10937.200874  10937.200874  485.712380  2.178953e-75
AGE         1.0     89.616596     89.616596    3.979802  4.660012e-02
DIS         1.0   1784.162442   1784.162442   79.233233  1.063395e-17
RAD         1.0     35.329641     35.329641    1.568961  2.109530e-01
TAX         1.0    323.682562    323.682562   14.374485  1.684257e-04
PTRATIO     1.0   1317.902599   1317.902599   58.527005  1.064683e-13
B           1.0    594.277671    594.277671   26.391398  4.025844e-07
LSTAT       1.0   2432.327444   2432.327444  108.017725  5.238497e-23
Residual  492.0  11078.784578     22.517855         NaN           NaN